// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace LanBackupAgent.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class IdentityResult
    {
        /// <summary>
        /// Initializes a new instance of the IdentityResult class.
        /// </summary>
        public IdentityResult() { }

        /// <summary>
        /// Initializes a new instance of the IdentityResult class.
        /// </summary>
        public IdentityResult(bool? succeeded = default(bool?), IList<IdentityError> errors = default(IList<IdentityError>))
        {
            Succeeded = succeeded;
            Errors = errors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "succeeded")]
        public bool? Succeeded { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<IdentityError> Errors { get; private set; }

    }
}
