// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace LanBackupAgent.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PaginatedListBackupConfigurationString
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PaginatedListBackupConfigurationString class.
        /// </summary>
        public PaginatedListBackupConfigurationString() { }

        /// <summary>
        /// Initializes a new instance of the
        /// PaginatedListBackupConfigurationString class.
        /// </summary>
        public PaginatedListBackupConfigurationString(int? pi = default(int?), int? tp = default(int?), IList<BackupConfiguration> recs = default(IList<BackupConfiguration>), bool? hp = default(bool?), bool? hn = default(bool?))
        {
            Pi = pi;
            Tp = tp;
            Recs = recs;
            Hp = hp;
            Hn = hn;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pi")]
        public int? Pi { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tp")]
        public int? Tp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recs")]
        public IList<BackupConfiguration> Recs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hp")]
        public bool? Hp { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hn")]
        public bool? Hn { get; private set; }

    }
}
