// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace LanBackupAgent.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class User
    {
        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User() { }

        /// <summary>
        /// Initializes a new instance of the User class.
        /// </summary>
        public User(string email = default(string), string password = default(string), string newPassword = default(string), bool? isAdmin = default(bool?), bool? succeeded = default(bool?), bool? isLockedOut = default(bool?))
        {
            Email = email;
            Password = password;
            NewPassword = newPassword;
            IsAdmin = isAdmin;
            Succeeded = succeeded;
            IsLockedOut = isLockedOut;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "newPassword")]
        public string NewPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAdmin")]
        public bool? IsAdmin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "succeeded")]
        public bool? Succeeded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isLockedOut")]
        public bool? IsLockedOut { get; set; }

    }
}
